# Generated by Django 5.1.6 on 2026-01-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='clients.order'),
        ),
    ]
