# Generated by Django 5.1.6 on 2026-01-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_product_model_and_stop_product_field'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product to deliver at this stop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stops', to='clients.product'),
        ),
    ]
