# Generated by Django 5.1.6 on 2026-01-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_routestop_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Warehouse name (e.g., 'Main Depot - Montreal')", max_length=200)),
                ('code', models.CharField(help_text="Warehouse code (e.g., 'MTL-01')", max_length=20, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('has_coordinates', models.BooleanField(default=False)),
                ('capacity_tonnes', models.DecimalField(decimal_places=2, help_text='Total storage capacity in tonnes', max_digits=12)),
                ('current_stock_tonnes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('operating_hours_start', models.TimeField(default='07:00:00', help_text='Warehouse opening time')),
                ('operating_hours_end', models.TimeField(default='18:00:00', help_text='Warehouse closing time')),
                ('operates_weekends', models.BooleanField(default=False)),
                ('manager_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/main warehouse for routes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='return_to_warehouse',
            field=models.BooleanField(default=True, help_text='Whether route returns to origin warehouse'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, help_text='Ending warehouse if different from origin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_routes', to='route.warehouse'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_warehouse',
            field=models.ForeignKey(blank=True, help_text='Starting warehouse/depot for this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_routes', to='route.warehouse'),
        ),
    ]
