# Generated by Django 5.1.6 on 2026-01-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('route', '0003_warehouse_route_return_to_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=6, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude in meters', max_digits=8, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=6, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='Compass heading in degrees (0-360)', max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recorded_at', models.DateTimeField(help_text='Device timestamp when position was recorded')),
                ('is_moving', models.BooleanField(default=True)),
                ('is_ignition_on', models.BooleanField(default=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Mobile device battery level (0-100)', null=True)),
                ('source', models.CharField(default='mobile_app', help_text='Source of position data (mobile_app, gps_device, etc.)', max_length=50)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_positions', to='driver.driver')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_positions', to='route.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_positions', to='driver.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Entered Geofence'), ('exit', 'Exited Geofence'), ('dwell', 'Dwelling in Geofence')], max_length=10)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('distance_meters', models.DecimalField(decimal_places=2, help_text='Distance from stop location in meters', max_digits=10)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='route.routestop')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='route.vehicleposition')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['vehicle', '-recorded_at'], name='route_vehic_vehicle_647b31_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['route', '-recorded_at'], name='route_vehic_route_i_3c8d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['-recorded_at'], name='route_vehic_recorde_f0a230_idx'),
        ),
    ]
