# Generated by Django 5.1.6 on 2025-12-31 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(blank=True, help_text='Client city', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Client postal code', max_length=20)),
                ('country', models.CharField(default='Canada', help_text='Client country', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Full address if available')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('priority', models.CharField(blank=True, choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], help_text='Auto-calculated based on predicted reorder date urgency', max_length=10, null=True)),
                ('has_contract', models.BooleanField(default=False, help_text='Has long-term contract')),
                ('historical_monthly_usage', models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly usage in tonnes (auto-calculated from order history)', max_digits=10, null=True)),
                ('last_usage_calculation', models.DateTimeField(blank=True, help_text='When usage was last calculated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('predicted_next_order_days', models.DecimalField(blank=True, decimal_places=2, help_text='AI-predicted days until next order', max_digits=5, null=True)),
                ('predicted_next_order_date', models.DateTimeField(blank=True, help_text='Expected next order date based on AI prediction', null=True)),
                ('prediction_confidence_lower', models.DecimalField(blank=True, decimal_places=2, help_text='Lower confidence interval (days)', max_digits=5, null=True)),
                ('prediction_confidence_upper', models.DecimalField(blank=True, decimal_places=2, help_text='Upper confidence interval (days)', max_digits=5, null=True)),
                ('last_prediction_update', models.DateTimeField(blank=True, help_text='When prediction was last calculated', null=True)),
                ('prediction_accuracy_score', models.DecimalField(blank=True, decimal_places=2, help_text='Historical accuracy of predictions for this client (0-100)', max_digits=5, null=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_number', models.CharField(db_index=True, help_text='Client order number (multiple batches may share same number)', max_length=100)),
                ('expedition_number', models.CharField(blank=True, help_text='Expedition/delivery number', max_length=100)),
                ('product_name', models.CharField(blank=True, help_text='Product delivered', max_length=200)),
                ('sales_order_creation_date', models.DateTimeField(db_index=True, help_text='When the order was created/placed')),
                ('total_amount_ordered_tm', models.DecimalField(decimal_places=2, help_text='Total amount ordered in tonnes', max_digits=10)),
                ('total_amount_delivered_tm', models.DecimalField(decimal_places=2, help_text='Total amount delivered in tonnes (may be from multiple batches)', max_digits=10)),
                ('promised_expedition_date', models.DateTimeField(blank=True, help_text='Promised/expected delivery date', null=True)),
                ('actual_expedition_date', models.DateTimeField(blank=True, db_index=True, help_text='Actual delivery date (last batch if multiple)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Order status (delivered when actual_expedition_date is set)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
            ],
            options={
                'ordering': ['-sales_order_creation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['city', 'country'], name='clients_cli_city_92d194_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'sales_order_creation_date'], name='clients_ord_client__8bd72e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_order_number'], name='clients_ord_client__742eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'actual_expedition_date'], name='clients_ord_status_cd5a7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('client_order_number', 'expedition_number')},
        ),
    ]
