# Generated by Django 5.1.6 on 2026-01-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('order_count_at_cache', models.IntegerField(help_text='Number of orders when cache was generated')),
                ('last_order_date', models.DateTimeField(blank=True, help_text='Latest order date when cache was generated', null=True)),
            ],
            options={
                'db_table': 'analytics_cache',
                'indexes': [models.Index(fields=['cache_key', 'updated_at'], name='analytics_c_cache_k_c336c9_idx')],
            },
        ),
    ]
