# Generated by Django 5.1.6 on 2026-01-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('code', models.CharField(blank=True, help_text='Product code/SKU', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('soya_meal', 'Soya Meal'), ('trituro', 'Trituro'), ('dairy_trituro', 'Dairy Trituro'), ('oil', 'Soya Oil'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(choices=[('tonnes', 'Tonnes'), ('kg', 'Kilograms'), ('liters', 'Liters')], default='tonnes', max_length=20)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requires_bulk_delivery', models.BooleanField(default=True, help_text='Requires bulk truck delivery')),
                ('min_order_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order quantity', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
