# Generated by Django 5.1.6 on 2025-12-31 04:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('route', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bulk_truck', 'Bulk Truck'), ('tank_oil', 'Oil Tank'), ('tank_blower', 'Blower Compartment Tank'), ('box_truck', 'Box Truck (Tote Bags)'), ('dump_truck', 'Dump Truck')], max_length=20)),
                ('capacity_tonnes', models.DecimalField(decimal_places=2, help_text='Vehicle capacity in tonnes', max_digits=8)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('has_gps_tracking', models.BooleanField(default=False)),
                ('electronic_log_device', models.CharField(blank=True, help_text='Electronic truck log device ID', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('out_of_service', 'Out of Service')], default='active', max_length=20)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance_due', models.DateTimeField(blank=True, null=True)),
                ('odometer_km', models.IntegerField(default=0, help_text='Current odometer reading in KM')),
                ('fuel_efficiency_l_per_100km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('co2_emissions_factor', models.DecimalField(decimal_places=4, default=Decimal('2.31'), help_text='CO2 kg per liter of diesel', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vehicle_type', 'vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='assigned', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_quantity_delivered', models.DecimalField(decimal_places=2, default=0, help_text='Total delivered in tonnes', max_digits=10)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('fuel_consumed_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('co2_emissions_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gps_tracking_data', models.JSONField(blank=True, default=dict, help_text='GPS data from electronic truck log')),
                ('notes', models.TextField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='route.route')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.DecimalField(blank=True, decimal_places=2, help_text='Planned quantity in tonnes', max_digits=10, null=True)),
                ('quantity_delivered', models.DecimalField(blank=True, decimal_places=2, help_text='Actual delivered quantity in tonnes', max_digits=10, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, choices=[('silo_to_silo', 'Silo to Silo (Bulk)'), ('compartment_unload', 'Tank Compartment Unload'), ('tote_delivery', 'Tote Bag Delivery')], default='silo_to_silo', max_length=20, null=True)),
                ('signature', models.TextField(blank=True, help_text='Base64 encoded signature', null=True)),
                ('delivery_confirmation_number', models.CharField(blank=True, max_length=50)),
                ('quality_check_passed', models.BooleanField(blank=True, null=True)),
                ('customer_rating', models.IntegerField(blank=True, help_text='1-5 rating from customer', null=True)),
                ('notes', models.TextField(blank=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='driver.delivery')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('product_type', models.CharField(choices=[('all_trituro_44', 'All Trituro 44'), ('all_dairy_trituro', 'All Dairy Trituro'), ('all_oil', 'All Oil'), ('combined', 'Combined')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tonnes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('km_per_tonne', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_co2_emissions_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_delivery_time_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('on_time_delivery_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('metric_type', 'product_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50)),
                ('can_drive_vehicle_types', models.JSONField(default=list, help_text='List of vehicle types this driver is certified for')),
                ('is_available', models.BooleanField(default=True)),
                ('current_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries_completed', models.IntegerField(default=0)),
                ('total_km_driven', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_delivery_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='driver.vehicle')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='driver.driver'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='driver.vehicle'),
        ),
    ]
